export const errorStatus = {
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_EXISTED: 'EMAIL_EXISTED',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_TOKEN_PAYLOAD: 'INVALID_TOKEN_PAYLOAD',
  NO_CREDENTIALS: 'NO_CREDENTIALS',
  UNREGISTERED: 'UNREGISTERED',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  RESET_PASSWORD_EXPIRED: 'RESET_PASSWORD_EXPIRED',
  NO_PERMISSIONS: 'NO_PERMISSIONS',
  BAD_REQUEST: 'BAD_REQUEST',
};
