export const successStatus = {
  SIGN_UP_SUCCESSFULLY: 'SIGN_UP_SUCCESSFULLY',
  SIGN_IN_SUCCESSFULLY: 'SIGN_IN_SUCCESSFULLY',
  REFRESH_SUCCESSFULLY: 'REFRESH_SUCCESSFULLY',
  FORGOT_PASSWORD_SUCCESSFULLY: 'FORGOT_PASSWORD_SUCCESSFULLY',
  RESET_PASSWORD_SUCCESSFULLY: 'RESET_PASSWORD_SUCCESSFULLY',
};
